-- SELECT * FROM customers;
-- SELECT customers.first_name, customers.email FROM customers;
-- SELECT product_name,price from products;
-- SELECT * FROM departments;
--
-- 19-- ========== EXERCISE 1.2: WHERE Clause ==========
-- 20-- 5. Find all employees with salary greater than 60000
-- SELECT * FROM employees
--     WHERE salary > 60000;
-- -- 6. Find all products priced under $50
-- SELECT * FROM products
--     WHERE price < 50;
-- 22-- 7. Find all customers from 'New York'
-- SELECT * FROM customers
--     WHERE city = 'New York';
-- 23-- 8. Find all orders with status 'Delivered'
-- SELECT * FROM orders
--     WHERE status = 'Shipped';
-- 24-- 9. Find all employees hired after '2021-01-01'
-- SELECT * FROM employees
--     WHERE hire_date > '2021-01-01';
-- 25-- 10. Find products in the Electronics category (category_id = 1)
-- SELECT * FROM products
-- WHERE category_id = 1;
--
--
--
-- 28-- ========== EXERCISE 1.3: WHERE with Multiple Conditions ==========
-- 29-- 11. Find employees in department_id 2 with salary > 65000
-- SELECT * FROM employees
--     WHERE department_id = 2
--         AND  salary > 65000;
-- 30-- 12. Find products with price between $20 and $100
-- SELECT * FROM products
--     WHERE price BETWEEN  20 AND 100;
--
-- 31-- 13. Find customers from either 'New York' or 'Los Angeles'
-- SELECT * FROM customers
--     WHERE city = 'New York' OR city =  'Los Angeles';
--
-- 32-- 14. Find orders placed in 2023 with status 'Delivered'
-- SELECT * FROM orders
--     WHERE extract(YEAR FROM order_date) = 2023 AND status = 'Delivered';
-- 33-- 15. Find products NOT in category 1 (Electronics)
-- SELECT * FROM products
-- WHERE category_id != 1;
--
--
--
-- 36-- ========== EXERCISE 1.4: Sorting and Limiting ==========
-- 37-- 16. List all employees ordered by salary (highest first)
-- SELECT * FROM employees
--     ORDER BY salary DESC;
-- 38-- 17. List all products ordered by price (lowest first)
-- SELECT * FROM products
--     ORDER BY price asc;
-- 39-- 18. Find the 5 most expensive products
-- SELECT * FROM products
--     ORDER BY price DESC  LIMIT 5;
-- 40-- 19. Find the 10 newest customers (by registration_date)
-- SELECT * FROM customers
--     ORDER BY registration_date DESC LIMIT 10;
-- 41-- 20. List employees alphabetically by last name
-- SELECT * FROM employees
--     ORDER BY last_name ASC;
-- 42
--
--
-- 121-- ============================================
-- 122-- LEVEL 2: INTERMEDIATE - JOINS
-- 123-- ============================================
-- 124
-- 125-- ========== EXERCISE 2.1: INNER JOIN ==========
-- 126-- 21. List all employees with their department names
-- SELECT E.first_name, E.last_name, E.email, D.dept_name  FROM employees as E
--     JOIN departments  as D
--         ON D.id = E.department_id;
-- 127-- 22. List all products with their category names
-- SELECT * FROM products p
--     JOIN categories c on p.category_id = c.id;
-- 128-- 23. List all orders with customer names
-- SELECT * FROM orders O
--     JOIN customers as C On O.customer_id = C.id;
-- 129-- 24. Find employee names and their manager names
-- SELECT * FROM employees
--     JOIN public.departments d on d.id = employees.department_id;
--
--
-- 130-- 25. List order items with product names and prices
-- SELECT * FROM orders AS O
--     JOIN products AS P ON O.id = P.id;
-- 133-- ========== EXERCISE 2.2: Multiple JOINS ==========
-- 134-- 26. List all order items with: order date, customer name, and product name
-- ---ORDER CUSTOMER, PRODUCT
-- SELECT   o.order_date, c.first_name || ' ' || c.last_name as customer_name,  p.product_name,oi.quantity FROM order_items oi
--         INNER JOIN orders o ON oi.order_id = o.id
--         INNER JOIN customers c ON c.id = o.customer_id
--     INNER JOIN products p ON oi.product_id = p.id;
--
--
--
--
-- 135-- 27. Show employees with department name and location
-- SELECT  e.first_name, e.last_name,  d.dept_name, d.location  from employees e
--     INNER JOIN departments AS d ON d.id = e.department_id;
--
-- 136-- 28. List products with category name and description
-- SELECT p.product_name, p.price, c.category_name, c.description FROM products p
--     INNER JOIN categories as c ON p.category_id = c.id;
-- 137-- 29. Show order details: customer name, order date, product name, quantity
-- SELECT --- customer name order date product name qunaitity
--     c.first_name || ' ' || c.last_name as customer_name,
--     O.order_date as orderDate,
--     P.product_name as ProductName,
--     OI.quantity as Quanitity FROM orders O
--     INNER JOIN customers as C ON O.customer_id = C.id
--     INNER JOIN  order_items as OI ON O.id = OI.order_id
--     INNER JOIN products as P ON P.id = OI.product_id ;
--
--
--
-- 138-- 30. Find all Employees with their department and manager (if they have one)
-- SELECT e.first_name || ' ' || e.last_name as employee,
--        de.dept_name, m.first_name || ' ' || m.last_name as manager
-- FROM employees  as E
--      INNER JOIN departments as DE ON E.department_id = DE.id
--      INNER JOIN employees as m ON m.manager_id = e.manager_id;
--
--
-- 139
-- 140
-- 141-- ========== EXERCISE 2.3: LEFT JOIN ==========
-- 142-- 31. List all customers and their orders (including customers with no orders)
-- SELECT c.first_name, c.last_name,o.id as order_id,o.order_date FROM customers c
--     LEFT JOIN orders as o  on c.id= o.customer_id;
-- 143-- 32. Show all products and their order items (including never-ordered products)
-- SELECT  p.product_name, oI.order_id, oi.quantity FROM products p
--     LEFT JOIN order_items oI ON p.id = oI.product_id;
-- 144-- 33. List all employees and their subordinates (including those without subordinates)
--  --- LEFT EMPLOYEE
-- SELECT  m.first_name || ' ' || m.last_name as manager, e.first_name || ' ' || e.last_name as employee FROM employees m
--     LEFT JOIN  employees E On m.id = E.manager_id
-- WHERE m.id IN (SELECT DISTINCT manager_id FROM employees WHERE manager_id IS NOT NULL);
--
-- SELECT * FROM employees;
-- -- SELECT * FROM employees WHERE departments IN ('Sales', 'Marketing', 'IT');
-- 145-- 34. Show all categories and their products (including empty categories)
--
--
--
-- 146-- 35. List departments with employee count (including departments with 0 employees)
-- SELECT count(e.id) AS EMLOYEE_COUNT FROM departments d
--     FULL JOIN public.employees e on d.id = e.department_id
-- group by d.id , d.dept_name;
--
-- 276-- ========== EXERCISE 3.1: Basic Aggregation ==========
-- 277-- 36. Count total number of employees
-- SELECT count(employees.id) as Employee_CoUNT FROM employees;
-- 278-- 37. Find the average salary of all employees
-- SELECT AVG(salary) FROM employees;
-- 279-- 38. Find the highest and lowest product prices
-- 280-- 39. Calculate total revenue from all orders
-- 281-- 40. Count how many orders each customer has placed
--
--
-- -- ============================================
-- 273-- LEVEL 3: ADVANCED - AGGREGATION & GROUP BY
-- 274-- ============================================
-- 275
-- 276-- ========== EXERCISE 3.1: Basic Aggregation ==========
-- 277-- 36. Count total number of employees
--
-- SELECT  count(employees.id) FROM employees;
-- 278-- 37. Find the average salary of all employees
-- SELECT AVG(employees.salary) FROM employees;
-- 279-- 38. Find the highest and lowest product prices
-- SELECT min(products.price) as Min_price , max(products.price) FROM products;
-- 280-- 39. Calculate total revenue from all orders
-- SELECT sum(orders.total_amount)as TOtal_revenue FROM orders;
--
-- 281-- 40. Count how many orders each customer has placed
-- SELECT  orders.customer_id,
--         count(*) as number_of_order_placed_by_customer FROM orders GROUP BY customer_id;
-- 282
-- 283
-- 284-- ========== EXERCISE 3.2: GROUP BY ==========
-- 285-- 41. Count employees per department
-- SELECT d.dept_name  , count(e.id)  FROM  departments d
--     LEFT JOIN employees e ON d.id = e.department_id
--     GROUP BY  d.dept_name;
--
-- SELECT d.dept_name , count(e.id)  FROM departments as d
--      JOIN  employees as E ON d.id = e.department_id
-- GROUP BY d.dept_name;
--
--
-- SELECT * FROM employees;
-- SELECT * FROM departments;
--
-- 286-- 42. Calculate average salary per department
--  SELECT d.dept_name , avg(e.salary) FROM employees e
--      JOIN departments as d ON e.department_id = d.id
-- GROUP BY d.id, d.dept_name;
-- 287-- 43. Find total sales per product
-- SELECT p.product_name, sum(oi.unit_price * oi.quantity) as total_sales_per_product FROM order_items oi
--     JOIN orders o ON oi.order_id = o.id
--     JOIN products p ON p.id = oi.product_id
-- GROUP BY p.id,  product_name
-- ORDER BY total_sales_per_product DESC ;
--
--
-- 288-- 44. Count orders per customer
-- SELECT  c.first_name ||  ' ' || c.last_name as Fullname , count(o.id) FROM customers c
--     LEFT JOIN orders o ON  c.id = o.customer_id --- c
--     GROUP BY c.id;
--
--
-- 289-- 45. Find the number of products in each category
-- SELECT * FROM categories;
-- SELECT * FROM products;
--
-- SELECT c.id , c.category_name , count(p.id)
-- FROM categories c
--     LEFT JOIN products p ON c.id = p.category_id
--     GROUP BY c.id,  c.category_name;
--
--
-- 290
-- 291
-- 292-- ========== EXERCISE 3.3: HAVING Clause ==========
-- 293-- 46. Find departments with more than 2 employees
-- SELECT d.dept_name , count(e.id) as employee_count FROM employees e
--     LEFT JOIN departments d ON e.department_id = d.id
--     GROUP BY d.id, d.dept_name
--     HAVING count(e.id) > 2;
--
-- 294-- 47. Find products that have been ordered more than 5 times
-- SELECT p.product_name,  count(oi.id) FROM products p
--     INNER JOIN order_items oi   ON  p.id = oi.product_id
--     GROUP BY p.product_name HAVING count(oi.id ) > 3;
--
--
-- 295-- 48. Find customers who have placed more than 2 orders
-- -- customer  < 2 Orders
-- SELECT
--         c.first_name || ' ' || c.last_name as Full_name ,
--        count(o.id) FROM customers c
--     INNER JOIN orders o ON o.customer_id = c.id
--     GROUP BY Full_name
--         HAVING count(o.id) > 2;
--
--
--
--
-- 296-- 49. Find categories with average product price > $50
--
-- SELECT
--     c.category_name,
--     AVG(p.price)
-- FROM categories c
--     INNER JOIN products p ON c.id = p.category_id
--     GROUP BY c.id, c.category_name
-- HAVING AVG(p.price) > 50;
--
--
-- 297-- 50. Find departments with average salary > $65,000
--
-- SELECT d.dept_name,  AVG(e.salary) FROM departments d
--     INNER JOIN employees e ON e.department_id = d.id
--     GROUP BY d.id,  d.dept_name
--         HAVING avg(e.salary) > 65000;
--
--
--
--
--
-- 300-- ========== EXERCISE 3.4: Complex Aggregation ==========
-- 301-- 51. Find the top 5 customers by total spending
-- SELECT  c.id, c.first_name || ' ' || c.last_name as Full_name ,  Sum(o.total_amount) as total_spent FROM customers  c
--     INNER JOIN orders o ON  c.id = o.id
--     GROUP BY c.id
--        ORDER BY total_spent DESC
--        limit  5;
--
-- 302-- 52. Calculate monthly revenue for 2023
-- SELECT extract(Month FROM o.order_date ) as month,
--        SUM(o.total_amount) FROM orders o
-- WHERE extract(YEAR FROM o.order_date ) = 2023
--     GROUP BY month
--         ORDER BY month;
--
--
--
--
-- 303-- 53. Find products that have never been ordered
-- SELECT * FROM products pr
--     LEFT JOIN order_items o ON pr.id = o.product_id
-- WHERE o.id IS NULL;
--
-- 304-- 54. Find the most popular product (by quantity sold)
-- SELECT p.product_name,  count(p.id) as count, sum(oi.unit_price * oi.quantity) as total_sold FROM products p
--     JOIN order_items oi ON oi.product_id = p.id
--     GROUP BY p.product_name
--         ORDER BY total_sold desc
--                        LIMIT 1;
-- 305-- 55.  Calculate total sales per product category
-- -- Get total Revenue  - get cost
--
-- SELECT c.category_name, sum(o.quantity  * o.unit_price) as amount_of_sales FROM categories c
--     INNER JOIN  products p  ON p.category_id =c.id
--     INNER JOIN order_items o ON p.id = o.product_id
--     GROUP BY c.category_name
--     ORDER BY amount_of_sales desc;
--
--
--
--
-- 467-- ============================================
-- 468-- LEVEL 4: EXPERT - SUBQUERIES & ADVANCED
-- 469-- ============================================
-- 470
-- 471-- ========== EXERCISE 4.1: Subqueries ==========
-- 472-- 56. Find employees earning more than the average salary
-- SELECT
--     e.first_name || ' ' ||  e.last_name as name, salary
-- FROM employees e
--    WHERE e.salary > (SELECT AVG(salary) FROM employees);
--
--
--
-- 473-- 57. Find products more expensive than the average product in their category
-- SELECT p.product_name, p.price , c.category_name FROM products p
--     INNER JOIN categories c ON p.category_id  = c.id
--     WHERE p.price > (
--         SELECT avg(pr.price) FROM products pr
--                 WHERE pr.category_id = p.category_id );
--
--
--
-- 474-- 58. Find customers who have spent more than the average customer
-- --Question is How much diid the AVG Customer spent
-- SELECT  c.id, c.first_name || ' ' || c.last_name,  sum(o.total_amount) as total_order
-- FROM orders o
--     INNER JOIN customers c ON c.id = o.customer_id
--    where total_amount > (
--             SELECT AVG(oi.total_amount) from orders oi
--                     WHERE oi.customer_id = o.customer_id)
--     GROUP BY c.id;
--
--
--
-- -- 58. Find customers who have spent more than average
-- SELECT
--     c.first_name || ' ' || c.last_name as customer,
--     SUM(o.total_amount) as total_spent
-- FROM customers c
--          INNER JOIN orders o ON c.id = o.customer_id
-- GROUP BY c.id, c.first_name, c.last_name
-- HAVING SUM(o.total_amount) > (
--     SELECT AVG(customer_total)
--     FROM (
--              SELECT SUM(total_amount) as customer_total
--              FROM orders
--              GROUP BY customer_id
--          ) avg_spending
--
-- );
--
--
-- -- 59. Find the department with the highest average salary
--
-- SELECT d.dept_name, avg(e.salary) as avg_salary FROM departments d
--     INNER JOIN employees e ON d.id = e.department_id
--     GROUP BY d.dept_name
--     ORDER BY avg_salary desc limit 1;
--
--
--
--
--
-- 476-- 60. Find products that cost more than all products in the 'Books' category
--
-- select p.product_name, p.price from products p
--     WHERE p.price > (Select max(p.price) from products p
--                      where p.category_id = (Select c.id from categories c where category_name = 'Books'))
--         ORDER BY p.price DESC ;
--
-- -- SubQuery First
--
--
-- -- 61. Rank employees by salary within each department
--
-- SELECT e.first_name || ' ' || e.last_name as Full_name ,
--        e.salary , d.dept_name ,
--        rank() OVER (PARTITION BY department_id ORDER BY  salary desc ) salary_rank
-- FROM employees e
--     JOIN departments d ON e.department_id = d.id;
--
-- 1-- 63. Calculate running total of orders by date
--
-- SELECT extract(YEAR FROM o.order_date),
--        o.total_amount,
--        sum(o.total_amount) OVER (ORDER BY order_date) as running_total
-- FROM orders o
--     order by o.order_date;
--
--
-- SELECT first_name,
--        department_id,
--        salary,
--        avg(salary) OVER (PARTITION BY department_id ORDER BY first_name ASC ) dept_avg
--     FROM employees
--         GROUP BY first_name , department_id, salary;
--
--
-- SELECT order_date, total_amount,
--        SUM(total_amount) OVER (ORDER BY orders.order_date) as running_total
-- FROM orders ORDER BY order_date;;
--
-- 79-- 64. Find customers who ordered both Electronics AND Clothing
--
-- -- Customers who order both Electronic and Clothing
-- SELECT DISTINCT c.first_name || ' ' || c.last_name as Full_name
-- FROM customers c
-- WHERE c.id IN (
--         SELECT o.customer_id
--         FROM orders o
--         JOIN order_items oi ON o.id  = oi.order_id
--         JOIN products p ON oi.product_id = p.id
--         WHERE p.category_id = 1
--     )
--
-- AND c.id IN ( SELECT o.customer_id
--         FROM orders o
--         JOIN order_items oi ON o.id  = oi.order_id
--         JOIN products p ON oi.product_id = p.id
--         WHERE p.category_id = 2
-- );
--
--
-- SELECT employees.last_name FROM employees
-- WHERE id IN
-- (
--     SELECT o.customer_id FROM orders o
--     JOIN order_items oi ON o.id = oi.order_id
--     WHERE oi.quantity > 5
-- );
--
--
-- SELECT  e.first_name || ' ' || e.last_name as Employee_Full_name,
--         m.first_name || '' || m.last_name as Manager_Full_name,
--         e.hire_date as Employee_hired_date,
--         m.hire_date as Manager_hired_date from employees e
--     JOIN employees m  ON e.manager_id = m.id
--     WHERE extract(YEAR FROM e.hire_date) = extract(YEAR FROM m.hire_date) AND
--             extract(MONTH FROM e.hire_date) = extract(MONTH  FROM m.hire_date);
--
--
--
-- --- JOINS
--
-- SELECT    c.first_name ||  ' ' || c.last_name as customer_name  , SUM(o.total_amount)
-- FROM customers c
-- INNER JOIN orders o ON c.id = o.customer_id
-- GROUP BY customer_name ;
--
-- -- Takes customer and Order Matches Customer with Order Returns only customers that have order. and skips the ones that have no order
--
-- -- GEt all Product that have catergory
-- SELECT p.product_name, p.price, c.category_name, c.description
-- FROM products p
--  LEFT JOIN categories c ON p.category_id = c.id;
--
-- INSERT into products (id, product_name, category_id, price, stock_quantity) VALUES (93923, 'Microphone' ,  NULL, 12.99, 234);
-- INSERT into customers (first_name, last_name, email, city, country, registration_date) VALUES ('AHmed ' , 'ismail', 'Ahmedismail@gmail.com', 'Brooklpyn Park', 'USA', '2026-01-01' )
-- SELECT c.first_name ||  ' ' || c.last_name as customer_name ,
--         count( o.id) as order_count,  --- We return all the customers despite having orders or Not
--        c.email
-- FROM customers c
-- LEFT JOIN orders o ON c.id = o.customer_id
-- GROUP BY customer_name, c.email
-- ORDER BY  order_count desc;
--
--
-- SELECT c.first_name, c.last_name , o.order_date, o.total_amount from customers c
-- INNER JOIN orders o ON c.id = o.customer_id
-- WHERE c.city = 'New York'
-- ORDER BY o.order_date;
--
--
-- SELECT  c.first_name || ' ' || c.last_name as customer_name, o.order_date, p.product_name, oi.quantity
-- FROM customers c
-- INNER JOIN orders o ON o.customer_id= c.id
-- INNER JOIN order_items oi ON o.id = oi.order_id
-- INNER JOIN products p ON oi.product_id = p.id;
--
-- SELECT
--     p.product_name,
--     COUNT(oi.id) as times_ordered
-- FROM products p
-- LEFT JOIN order_items oi ON p.id = oi.product_id
-- GROUP BY p.id, p.product_name
-- ORDER BY times_ordered DESC;
--
-- SELECT
--    c.first_name || ' ' || c.last_name as customer_name,
--     AVG(o.total_amount) as avg_order_value
-- FROM customers c
-- INNER JOIN orders o ON c.id = o.customer_id
-- GROUP BY c.id, c.first_name, c.last_name
-- ORDER BY avg_order_value DESC;
--
--
-- SELECT p.*, c.* FROM products p
-- INNER JOIN categories c ON p.category_id = c.id
-- ORDER BY c.category_name, p.product_name;
--
--
-- SELECT c.first_name || ' '||  c.last_name as Full_name, o.order_date, o.total_amount FROM customers c
-- INNER JOIN orders o ON c.id = o.customer_id
-- WHERE c.city = 'New York'
-- ORDER BY o.order_date;
--
--
-- SELECT * FROM customers c
-- LEFT JOIN orders o ON c.id = o.customer_id
-- WHERE o.id  is  NULL;
--
--
-- SELECT c.first_name || ' ' || c.last_name as customer_name, o.order_date, p.product_name, oi.quantity FROM customers c
-- INNER JOIN orders o ON c.id = o.customer_id
-- INNER JOIN order_items oi ON o.id = oi.order_id
-- INNER JOIN  products p ON oi.product_id = p.id
-- ORDER BY o.order_date, c.last_name;
--
-- -- Self Joins
-- SELECT   e.first_name || ' ' || e.last_name as employee_name,   m.first_name || ' ' || m.last_name as manager_name
--  FROM employees e
-- LEFT JOIN employees m ON e.manager_id = m.id;
--
-- SELECT * FROM employees;
--
-- SELECT c.category_name, SUM(oi.quantity * oi.unit_price) as total_revenue
-- FROM categories c
-- LEFT  JOIN products p ON c.id = p.category_id
-- INNER JOIN order_items oi ON p.id = oi.product_id
-- GROUP BY c.category_name
-- ORDER BY total_revenue;
--
--
-- SELECT p.product_name,  count(oi.id ) as times_ordered
-- FROM products p
-- INNER JOIN order_items oi ON p.id = oi.product_id
-- GROUP BY p.product_name
-- ORDER BY times_ordered DESC;
--
--
-- SELECT c.first_name,  AVG(o.total_amount) as Avg_per_customer FROM orders o
-- INNER JOIN customers c ON o.customer_id = c.id
-- GROUP BY c.first_name
-- ORDER BY Avg_per_customer DESC;
--
--  --- Customers with orders (using IN)
-- SELECT  c.first_name || ' ' || c.last_name as customer_name FROM customers c
-- WHERE c.id IN (
--     select customer_id FROM orders
--     )
--
-- ORDER BY c.first_name DESC ;
--
-- --- -- Exercise 12: Employees above average salary
-- SELECT   e.first_name || ' ' || e.last_name as emp_name , e.salary FROM employees e
-- WHERE
--     e.salary  <  (SELECT AVG(em.salary) FROM employees em);
--
-- -- Exercise 13: Products never ordered
--
-- SELECT p.product_name, p.price FROM products p
-- WHERE p.id  IN (SELECT oi.product_id FROM order_items oi) ORDER BY p.price DESC;
--
--
-- SELECT p.product_name, p.price FROM products p
-- WHERE p.price = (SELECT MIN(p2.price) FROM products p2);
--
--
--
--
-- -- Exercise 15: Employee salary vs company average
--
--
-- SELECT e.salary as EMPLOYEE_SALARY ,
--      a.avg_salary as AVG_EMPLYEE_AVG,
--        e.salary - a.avg_salary AS difference  FROM employees e
-- CROSS JOIN ( SELECT avg(em.salary) as avg_salary from employees em ) a
-- WHERE e.salary - a.avg_salary > 1;
--
-- -- Products above category average
--
-- -- First we have to find every categeory average
--
-- SELECT  c.category_name, AVG(p.price) FROM products p
-- INNER JOIN categories c ON p.category_id = c.id
-- GROUP BY c.category_name;
--
-- SELECT p2.product_name, c.category_name, p2.price FROM products p2
-- INNER JOIN categories c ON p2.category_id = c.id
-- WHERE p2.price > (
--     SELECT AVG(p.price) FROM products p
--     WHERE p.category_id = c.id
--     )
-- ORDER BY c.category_name, p2.price DESC;
--
-- -- Exercise 17: Customers who bought Electronics (EXISTS)
--
-- SELECT DISTINCT c.first_name || ' ' || c.last_name as customer_name
-- FROM customers c
-- WHERE EXISTS(
--     SELECT 1 FROM ORDERS o
--     INNER JOIN order_items oi ON o.id = oi.order_id
--     INNER  JOIN products p ON oi.product_id = p.id
--     WHERE o.customer_id = c.id AND  p.category_id = 1
-- );
--
-- -- Exercise 18: Departments with no employees
--
-- SELECT d.dept_name FROM departments d
-- WHERE NOT EXISTS(
--     SELECT 1 FROM employees em
--              WHERE d.id = em.department_id
-- )
-- -- Exercise 19: Product rank within category (correlated subquery)
--
-- SELECT p.product_name, p.price, c.category_name , (
--         SELECT count(*) + 1 FROM  products p2
--         WHERE p2.category_id = p.category_id AND p2.price > p.price
--     ) as price_rank FROM  products p
-- INNER JOIN categories c ON p.category_id = c.id
-- ORDER BY c.category_name,  price_rank;
--
--
-- --- Employees above department average
--
-- SELECT e.first_name || ' ' || e.last_name as full_name , avg( e.salary),   d.dept_name FROM employees e
-- INNER JOIN departments d ON  e.department_id = d.id
-- GROUP BY full_name, d.dept_name;
--
-- -- Exercise 20: Employees above department average
--
-- SELECT  e.first_name || ' ' || e.last_name as full_name,
--          e.salary , d.dept_name,
--         (SELECT AVG(salary) FROM employees e2 WHERE  e2.department_id = e.department_id ) as dept_avg
-- FROM employees e
-- INNER JOIN departments d ON  e.department_id = d.id
-- WHERE e.salary > (
--             SELECT AVG(e3.salary) FROM employees e3
--             WHERE e3.department_id = e.department_id
--     )
-- ORDER BY d.dept_name, e.salary DESC;
--
-- --- Write a sql Query for the Highest  spenders and their orders:
-- -- Customers and Orders
--
--
-- SELECT hs.full_name, hs.Total_customer_order,   o.order_date, o.total_amount FROM (
--     SELECT c.id,  c.first_name || ' ' || c.last_name as full_name, SUM( o.total_amount) as Total_customer_order  FROM customers c
--     INNER JOIN orders o ON o.customer_id = c.id
--     GROUP BY full_name, c.id
--     HAVING SUM( o.total_amount) > 1000
-- ) hs
-- INNER JOIN orders o  ON hs.id = o.customer_id
-- ORDER BY hs.Total_customer_order DESC, o.order_date;
--
--
-- --- Customers who bought from 3+ categories
--
--
-- SELECT  c.first_name || ' ' || c.last_name as customer_name
-- FROM customers c
-- WHERE c.id IN (
--     SELECT o.customer_id from orders o
--     INNER JOIN order_items oi ON o.id = oi.order_id
--     INNER JOIN products p ON oi.product_id = p.id
--     GROUP BY o.customer_id
--     HAVING count(DISTINCT p.category_id) >= 3
--
-- )
-- GROUP BY  customer_name;
--
-- SELECT o.customer_id from orders o
-- INNER JOIN order_items oi ON o.id = oi.order_id
-- INNER JOIN products p ON oi.product_id = p.id
-- GROUP BY o.customer_id
-- HAVING count(DISTINCT p.category_id) >= 3;
--
-- SELECT
--    c.first_name || ' ' || c.last_name as customer_name,
--    COUNT(DISTINCT p.category_id) as category_count
-- FROM customers c
-- INNER JOIN orders o ON c.id = o.customer_id
-- INNER JOIN order_items oi ON o.id = oi.order_id
-- INNER JOIN products p ON oi.product_id = p.id
-- GROUP BY c.id, c.first_name, c.last_name
-- HAVING COUNT(DISTINCT p.category_id) >= 3 --- We add this To ge
-- ORDER BY category_count DESC;
--
--
-- --- Top 3 best-selling products
--
-- SELECT
--     p.product_name,  sum(oi.unit_price * oi.quantity ) as total_amount_spent,
--     sum(oi.quantity) as total_sum  FROM orders o
-- INNER JOIN order_items oi ON o.id = oi.order_id
-- INNER JOIN products p ON oi.product_id = p.id
-- ORDER BY total_sum desc limit 3;
--
-- SELECT
--    p.product_name,
--     total_sales.total_quantity_sold
-- FROM products p
-- INNER JOIN (
--     SELECT
--        product_id,
--         SUM(quantity) as total_quantity_sold
--     FROM order_items
--     GROUP BY product_id
--    ORDER BY total_quantity_sold DESC
--     LIMIT 3
-- ) total_sales ON p.id = total_sales.product_id
-- ORDER BY total_sales.total_quantity_sold DESC;
--
--
--
--
-- SELECT p.product_name, total_sales.total_quantity_sold  FROM products p
-- INNER JOIN  (
--     SELECT
--         product_id,
--         SUM(quantity) as total_quantity_sold
--     FROM order_items
--     GROUP BY product_id
--     ORDER BY total_quantity_sold DESC
--     LIMIT 3
-- ) as total_sales  ON p.id = total_sales.product_id
-- ORDER BY total_sales.total_quantity_sold DESC;
--
--
-- -- Exercise 24: Customers with 2+ orders AND $500+ spent
-- --
-- --
-- -- 1. UNDERSTAND: What am I looking for?
--    --  Customers Table customer name and their Orders
--     -- Need to count customer orders
-- -- 2. IDENTIFY: Which tables have this data?
--     -- Customer and Order table
-- -- 3. CONNECT: How do tables relate?
--     -- INNER JOIN
-- -- 4. FILTER: What conditions must be met?
--     -- With 2+ orders
-- -- 5. AGGREGATE: Do I need to count/sum/average?
--     -- Counting customers Orders
-- -- 6. BUILD: Write query piece by piece
--
--
-- SELECT c.id,
--        c.first_name || ' ' || c.last_name as Full_name ,
--         total_sale.total_spent,
--         total_sale.total_order
-- FROM customers c
-- INNER JOIN  (
--     SELECT  customer_id, count(customer_id) as total_order  , SUM(total_amount) as total_spent FROM orders
--     GROUP BY customer_id
--     HAVING  SUM(total_amount) >= 500 AND  count(customer_id) >= 2
-- ) as  total_sale ON c.id = total_sale.customer_id
-- ORDER BY total_sale.total_spent DESC;
--
--
-- -- Step 1: UNDERSTAND - What am I looking for?
-- -- Break down the question:
-- --
-- -- "Customers" → I need customer names/info
-- -- "with 2+ orders" → Need to COUNT orders per customer
-- -- "AND $500+ spent" → Need to SUM total spending per customer
-- --
-- -- Mental note: I need ONE row per customer with their stats.
--
--
-- -- Step 2: IDENTIFY - Which tables?
-- -- Ask yourself: "Where does each piece of data live?"
-- --
-- -- Customer names → customers table
-- --                                Order count → orders table (count how many)
-- -- Total spent → orders table (sum the amounts)
--
-- -- Step 3: CONNECT - How do tables relate?
-- -- customers.id = orders.customer_id
-- -- Simple! One customer can have many orders.
-- --
-- -- Step 4: FILTER - What conditions?
-- -- Two conditions:
-- --
-- -- COUNT(orders) > 2
-- -- SUM(total_amount) > 500
-- --
-- -- Step 5: AGGREGATE - What calculations?
-- --
-- -- COUNT(orders) for each customer
-- -- SUM(total_amount) for each customer
-- -- Must GROUP BY customer
--
-- SELECT
--     c.first_name || ' ' || c.last_name as customer_name,
--     COUNT(o.id) as order_count,
--     SUM(o.total_amount) as total_spent
-- FROM customers c
--          INNER JOIN orders o ON c.id = o.customer_id
-- GROUP BY c.id, c.first_name, c.last_name
-- HAVING COUNT(o.id) > 2 AND SUM(o.total_amount) > 500
-- ORDER BY total_spent DESC;
--
-- SELECT
--     c.first_name || ' ' || c.last_name as customer_name,
--     total_sale.total_order,
--     total_sale.total_spent
-- FROM customers c
--          INNER JOIN (
--     SELECT
--         customer_id,
--         COUNT(*) as total_order,
--         SUM(total_amount) as total_spent
--     FROM orders
--     GROUP BY customer_id
--     HAVING SUM(total_amount) > 500
--        AND COUNT(*) > 2
-- ) as total_sale ON c.id = total_sale.customer_id
-- ORDER BY total_sale.total_spent DESC;
--
--
--
--
-- SELECT  SUM(o.customer_id) as customer_order,  o.total_amount FROM orders o
-- GROUP BY o.total_amount;
--
-- -- Exercise 25: Categories above store average price
-- SELECT  AVG(pk.price) FROM products pk;
-- SELECT * FROM categories;
--
--
-- SELECT c.category_name, AVG(p.price),  (SELECT AVG(pl.price) FROM products pl) as store_avg FROM categories c
-- INNER JOIN products p  ON c.id = p.category_id
-- GROUP BY CUBE (c.category_name)
-- HAVING AVG(p.price) > (SELECT  AVG(pk.price) FROM products pk);
--
--
-- CREATE INDEX idx_orders_customer_id ON orders(customer_id);
-- DROP  INDEX  idx_orders_customer_id;
--
-- SELECT * FROM orders WHERE  customer_id = 1;
--
--
-- -- Exercise 26: Customers who bought BOTH Electronics AND Clothing
--
-- -- SELECT first_name || '' || last_name as full_name FROM customers c
-- -- INNER JOIN order_items oi ON  c.id = oi
--
-- -- GEt orders that are Only Electronics
-- SELECT DISTINCT (ca.first_name || ' ' || ca.last_name )as full_name FROM customers ca
-- INNER JOIN orders o2 ON ca.id = o2.customer_id
-- WHERE o2.id IN (SELECT o.id
--                 FROM orders o
--                          INNER JOIN order_items oi ON o.id = oi.order_id
--                          INNER JOIN products p ON oi.product_id = p.id
--                          INNER JOin categories c ON p.category_id = c.id
--                 WHERE c.category_name = 'Electronics'
--                    AND c.category_name = 'Clothing');
--
-- SELECT DISTINCT c.first_name || ' ' || c.last_name as full_name
-- FROM customers c
--          INNER JOIN orders o ON c.id = o.customer_id
--          INNER JOIN order_items oi ON o.id = oi.order_id
--          INNER JOIN products p ON oi.product_id = p.id
--          INNER JOIN categories cat ON p.category_id = cat.id
-- WHERE cat.category_name IN ('Electronics', 'Clothing')
-- ORDER BY full_name;
--
--
--
--
-- -- Exercise 26: Customers who bought BOTH Electronics AND Clothing
--
--
-- SELECT DISTINCT c.first_name || ' ' || c.last_name as full_name
-- FROM customers c
-- WHERE c.id IN (
--     SELECT o.customer_id FROM orders o
--         INNER JOIN order_items oi ON o.id = oi.order_id
--         INNER JOIN products p ON oi.product_id = p.id
--     WHERE p.category_id = 1
--     )
-- AND c.id IN  (
--     SELECT o.customer_id FROM orders o
--         INNER JOIN order_items oi ON o.id = oi.order_id
--          INNER JOIN products p ON oi.product_id = p.id
--     WHERE p.category_id = 2
--     );
--
-- SELECT c.category_name, p2.product_name ,p2.price FROM products p2
-- INNER JOIN categories c ON p2.category_id = c.id
-- WHERE p2.price > (
--     SELECT MAX(p.price ) as total_cost_of_all_books FROM products p
--     INNER JOIN categories c  ON p.category_id = c.id
--     WHERE category_name = 'Books'
--     GROUP BY c.category_name
-- )
--
-- SELECT
--     p.product_name,
--     p.price,
--     c.category_name
-- FROM products p
--          INNER JOIN categories c ON p.category_id = c.id
-- WHERE p.price > (
--     SELECT MAX(price)
--     FROM products p2
--              INNER JOIN categories c2 ON p2.category_id = c2.id
--     WHERE c2.category_name = 'Books'
-- )
-- ORDER BY p.price DESC;
--
-- SELECT c.category_name,
--        COUNT(p.id) as product_count,
--        ROUND(AVG(p.price), 2) as avg_price,
--        ROUND((SELECT AVG(price) FROM products), 2) as store_avg,
--        CASE
--            WHEN AVG(price) > ( SELECT AVG(price) FROM products)
--            THEN 'Above average'
--            ELSE  'Below Average'
--        END as comparison
-- FROM categories c
-- INNER JOIN products p ON c.id = p.category_id
-- group by c.category_name;
--
--
-- SELECT
--     c.category_name,
--     cu.country,
--     SUM(oi.quantity * oi.unit_price) AS total_sales,
--     COUNT(DISTINCT o.id) AS num_orders
-- FROM order_items oi
--          JOIN orders o ON oi.order_id = o.id
--          JOIN products p ON oi.product_id = p.id
--          JOIN categories c ON p.category_id = c.id
--          JOIN customers cu ON o.customer_id = cu.id
-- GROUP BY GROUPING SETS (
--     (c.category_name, cu.country),  -- by category and country
--     (c.category_name),               -- by category only
--     (cu.country),                    -- by country only
--     ()                               -- grand total
--     )
-- ORDER BY
--     GROUPING(c.category_name),
--     GROUPING(cu.country),
--     c.category_name,
--     cu.country;
--
--
--
-- SELECT
--     o.status,
--     TO_CHAR(o.order_date, 'YYYY-MM') AS order_month,
--     SUM(oi.quantity * oi.unit_price) AS total_sales,
--     COUNT(DISTINCT o.id) AS num_orders
-- FROM orders o
--          JOIN order_items oi ON o.id = oi.order_id
-- GROUP BY ROLLUP (o.status, TO_CHAR(o.order_date, 'YYYY-MM'))
--
--
-- SELECT department_id, SUM(salary)
-- FROM employees
-- GROUP BY department_id;
--
-- SELECT department_id, extract(YEAR FROM hire_date) as hire_yeaar,  SUM(salary)
-- FROM employees
-- GROUP BY ROLLUP (department_id, extract(YEAR FROM hire_date));
--
--
-- SELECT department_id,  EXTRACT(YEAR FROM hire_date) AS hire_year, SUM(salary)
-- FROM employees
-- GROUP BY CUBE (department_id, EXTRACT(YEAR FROM hire_date));
--
-- SELECT department_id, EXTRACT(YEAR FROM hire_date) AS hire_year, SUM(salary)
-- FROM employees
-- GROUP BY GROUPING SETS (
--     (department_id),    -- totals by department
--     (EXTRACT(YEAR FROM hire_date)),  -- totals by year
--     ()                  -- grand total
--     );
--
-- SELECT   extract(YEAR FROM hire_date) as date_ordered, count(id),
--     CASE
--         WHEN GROUPING(EXTRACT(YEAR FROM hire_date)) = 1 THEN 'Total'
--          ELSE CAST(EXTRACT(YEAR FROM hire_date) AS VARCHAR)
-- END as hire_year
-- FROM employees
-- GROUP BY GROUPING SETS  (
--         extract(YEAR FROM hire_date),
--         ()
--     );
--
-- SELECT * FROM employees;
--
--
--
--
--
-- SELECT department_id, manager_id, SUM(salary)
-- FROM employees
-- GROUP BY CUBE (department_id, manager_id);
--
--
--
-- SELECT department_id, manager_id, SUM(salary)
-- FROM employees
-- GROUP BY GROUPING SETS (
--     (department_id),
--     (manager_id)
--     );
--
-- WITH total_sales AS (
--     SELECT department_id, manager_id,  SUM(salary)
--     FROM employees
--     GROUP BY  department_id, manager_id
-- ), top_region as (
--     SELECT department_id, manager_id From total_sales
-- )
-- SELECT employees.manager_id FROM employees;
--
--
--
-- -- Sample sales data
-- CREATE TABLE sales (
--                        salesperson TEXT,
--                        region TEXT,
--                        month TEXT,
--                        amount NUMERIC
-- );
--
-- INSERT INTO sales VALUES
--                       ('Alice', 'East', 'March', 123000)
--
--
--
--
-- SELECT
--     region,
--     month,
--     total_sales,
--     AVG(total_sales) OVER (PARTITION BY month) as region_avg
-- FROM (
--          SELECT region, month, SUM(amount) as total_sales
--          FROM sales
--          GROUP BY region, month
--      ) aggreated;
--
-- SELECT sales.salesperson ,
--        month,
--        amount,
--        row_number() over (PARTITION BY salesperson ORDER BY month) as row_num,
--        rank() over (PARTITION BY salesperson ORDER BY amount) as rank_num,
--        LAG(amount) over (PARTITION BY salesperson ORDER BY amount) as prev_amount,
--
-- from sales
--
--
--
-- SELECT sales.salesperson ,
--        month,
--        amount,
--        row_number() over (PARTITION BY salesperson ORDER BY month) as row_num,
--       SUM(amount) over (PARTITION BY  salesperson ORDER By month) as total_sales
-- --        rank() over (PARTITION BY region ORDER BY amount) as rank_num
--
--
-- from sales;
--
-- SELECT sales.salesperson, SUM(amount) as High_sales_person FROM sales
-- GROUP BY sales.salesperson
-- limit 1;
--
--
-- SELECT * FROM employees;
-- CREATE TABLE employees_2021 (
--
--                                     id SERIAL PRIMARY KEY,
--                                     first_name VARCHAR(50) NOT NULL,
--                                     last_name VARCHAR(50) NOT NULL,
--                                     email VARCHAR(100),
--                                     department_id INTEGER REFERENCES departments(id),
--                                     manager_id INTEGER REFERENCES employees(id),
--                                     salary DECIMAL(10, 2),
--                                     hire_date DATE
-- );
--
--
--
--
-- INSERT INTO employees_2021 (first_name, last_name, email, department_id, manager_id, salary, hire_date)
-- SELECT first_name,
--        last_name,
--        email,
--        department_id,
--        manager_id,
--        salary,
--        hire_date FROM EMPLOYEES WHERE extract(YEAR FROM employees.hire_date) = 2021;
--
--
-- SELECT * FROM employees_2021;
--
--
--
-- SELECT e_202.first_name || ' ' ||  e_202.last_name as full_name  , e_202.salary  FROM employees_2020 e_202
-- UNION
-- SELECT  e_2021.first_name || ' ' || e_2021.last_name as full_name  , e_2021.salary FROM employees_2021 e_2021
-- order by  full_name desc;
--
--
--
--
-- SELECT e_202.first_name || ' ' ||  e_202.last_name as full_name  , e_202.salary , 'LEFT' as status  FROM employees_2020 e_202
-- except
-- SELECT  e_2021.first_name || ' ' || e_2021.last_name as full_name  , e_2021.salary FROM employees_2021 e_2021
--
--
--
-- WITH employees_2020 AS (
--     SELECT *
--     FROM employees
--     WHERE hire_date >= DATE '2020-01-01'
--       AND hire_date <  DATE '2021-01-01'
-- )
-- SELECT *
-- FROM employees_2020;
--
--
-- SELECT *
-- FROM employees
-- WHERE hire_date >= DATE '2020-01-01'
--   AND hire_date <  DATE '2021-01-01'
--     )
--
--
-- WITH
--     high_salary AS (
--         SELECT *
--         FROM employees
--         WHERE salary > 70000
--     ),
--     engineering AS (
--         SELECT *
--         FROM departments
--         WHERE dept_name = 'Sales'
--     )
-- SELECT e.first_name, e.salary
-- FROM high_salary e
--          JOIN engineering d
--               ON e.department_id = d.id;
--
--
--
-- WITH dept_avg AS (
--     SELECT
--         department_id,
--         AVG(salary) AS avg_salary
--     FROM employees
--     GROUP BY department_id
-- )
-- SELECT * from dept_avg
--          WHERE avg_salary > 65000
-- ORDER BY department_id asc ;
--
--
-- WITH dept_avgs AS (
--     SELECT  e.id, e.first_name, e.department_id, e.salary, AVG(e.salary) OVER (PARTITION BY e.department_id) as dept_avg_salary FROm employees e
-- ) , depts_row AS (
--     SELECT id,  dept_name
--     FROM departments
--
--     )
-- SELECT *
-- FROM dept_avgs
-- JOIN depts_row ON dept_avgs.department_id = depts_row.id
-- WHERE salary > dept_avg_salary;
--
-- WITH customer_categories AS (
--     SELECT DISTINCT
--         o.customer_id,
--         p.category_id
--     FROM orders o
--              JOIN order_items oi ON o.id = oi.order_id
--              JOIN products p ON oi.product_id = p.id
-- )
-- SELECT * FROM customer_categories;
--
-- WITH customer_avg_orders AS (
--     SELECT
--         c.id,
--         c.first_name || ' ' || c.last_name as customer_name,
--         AVG(o.total_amount) as avg_order_value  -- Calculate avg per customer
--     FROM customers c
--              INNER JOIN orders o ON c.id = o.customer_id
--     GROUP BY c.id, c.first_name, c.last_name  -- One row per customer
-- ),percentile_75 AS (
--     SELECT
--     PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY avg_order_value) as p75_value
--     FROM customer_avg_orders
--     )
-- SELECT
--     cao.customer_name,
--     ROUND(cao.avg_order_value, 2) as avg_order_value,
--     'Top 25%' as percentile
-- FROM customer_avg_orders cao
--          CROSS JOIN percentile_75 p  -- Brings in the threshold value
-- WHERE cao.avg_order_value >= p.p75_value  -- Filter top 25%
-- ORDER BY cao.avg_order_value DESC;
--
-- SELECT  * FROM employees_2021;
--
-- update employees_2020 set hire_date = '2023-01-23', id= 33  where id = 1;
--
-- WITH delete_row_and_Insert_into_employee_2020 AS (
--     DELETE FROM employees_2020
--            WHERE id = 33
--            returning  *
-- )
-- INSERT INTO employees_2021
-- SELECT * FROM delete_row_and_Insert_into_employee_2020;
--
--
-- CREATE TABLE World_flag (
--     _id NUMERIC(4,2) NOT NULL ,
--     country_name varchar(10) NOT NULL
-- )
--
--
-- INSERT INTO World_flag (_id, country_name)
-- VALUES (12.22, 'USA')
--
-- SELECT * FROM UFA_CUP;
--
--
-- CREATE TABLE UFA_CUP (
--                             _id BIGINT GENERATED ALWAYS AS IDENTITY ,
--                             country_name varchar(10) NOT NULL
-- );
--
--
--
-- CREATE TABLE PAYMENTS (
--     _id UUID PRIMARY KEY DEFAULT gen_random_v4(),
--     payment_id BIGINT generated always as identity (START WITH  3001),
--     amount NUMERIC(12,2) NOT NULL ,
--     payer_name varchar(100)
-- )
--
-- INSERT INTO PAYMENTS ( amount, payer_name)
-- VALUES (1023, 'Mohamed Abdullahi')
--
-- SELECT * FROM PAYMENTS
--
-- SELECT '12.34'::float8::numeric::money;
-- SELECT char_length('hello') ;
--
-- SELECT '2026-01-19 02:00'::timestamptz AT TIME ZONE 'America/CHICAGO';
--
--
--
-- CREATE TABLE meetings (
--                           id SERIAL PRIMARY KEY,
--                           title TEXT,
--                           start_time TIMESTAMPTZ
-- );
--
-- -- Stored in UTC automatically
-- INSERT INTO meetings(title, start_time)
-- VALUES
--     ('ND Meeting', '2026-01-20 14:00:00-5'); -- EST
--
--
-- -- Query in local timezone
-- SELECT id, title, start_time AT TIME ZONE 'America/NEW_YORK' AS ny_time,
--        start_time AT TIME ZONE 'America/Los_Angeles' AS la_time,
--        start_time AT TIME ZONE 'America/CHICAGO' AS ci_time
-- FROM meetings;
--
--
-- CREATE TABLE payments (
--                           id BIGSERIAL PRIMARY KEY,
--                           user_id UUID NOT NULL,
--                           amount NUMERIC(12,2) NOT NULL,
--                           currency CHAR(3) NOT NULL DEFAULT 'USD',
--                           payment_time TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- store UTC
--                           status VARCHAR(20) NOT NULL DEFAULT 'pending'
-- );
--
--
-- INSERT INTO payments (user_id, amount, payment_time)
-- VALUES ('3fa85f64-5717-4562-b3fc-2c963f66afa6', 2290.00, '2026-01-19 02:27:28-6');
-- INSERT INTO payments(user_id, amount, payment_time)
-- VALUES ('3fa85f64-5717-4562-b3fc-2c963f66afa6', 12220.00, '2026-01-19T21:27:28Z'); -- Z = UTC
--
--
--
-- SELECT id, user_id, amount,
--        payment_time AT TIME ZONE 'America/CHICAGO' AS mn_time
-- FROM payments;
--
-- SELECT '{"bar": "baz", "balance": 7.77, "active": false}'::json;
--
-- SELECT '[1,2,3]'::jsonb @> '[1,3]'::jsonb;  -- true
-- SELECT '{"a":1, "b":2}'::jsonb @> '{"b":2}'::jsonb;  -- true
--
--
-- CREATE TABLE paymentK (
--                           id SERIAL PRIMARY KEY,
--                           user_id UUID,
--                           details JSONB
-- );
-- INSERT INTO paymentK (user_id, details)
-- VALUES (
--            '3fa85f64-5717-4562-b3fc-2c963f66afa6',
--            '{
--              "amount": 190.00,
--              "currency": "USD",
--              "method": "card",
--              "date": "2026-01-19T16:27:28-06:00"
--            }'::jsonb
--        );
--
-- INSERT INTO paymentK (user_id, details)
-- VALUES (
--            '3fa85f64-5717-4562-b3fc-2c963f66afa6',
--            '{
--              "amount": 190.00,
--              "currency": "USD",
--              "method": "card",
--              "date": "2026-01-19T16:27:28-06:00",
--               "name" : {
--                   "firstname" : "Mohamed"
--               }
--            }'::jsonb
--        );
--
--
-- SELECT  *  FROM paymentK;
-- SELECT details->'method' as MEthod, details->>'amount' FROM paymentK;
-- SELECT details->'method' AS payment_method
-- FROM paymentK;
--
--
-- UPDATE paymentK
-- set details['name']['firstname'] = '"Ahmedsddas SImail"'
-- WHERE details['name']['firstname'] = '"AhmeK SImail"' AND user_id ='3fa85f64-5717-4562-b3fc-2c963f66afa6' AND id = 3
--
--
-- SELECT jsonb_build_object(
--                'user', user_id,
--                'amount', details->>'amount',
--                'currency', details->>'currency'
--        ) AS payment_info
-- FROM paymentK;
--
-- SELECT jsonb_agg(
--                jsonb_build_object(
--                        'user', user_id,
--                        'amount', details->>'amount'
--                )
--        ) AS all_payments
-- FROM paymentK;
--
-- CREATE TABLE users (
--                        id SERIAL PRIMARY KEY,
--                        profile JSONB
-- );
--
-- INSERT INTO users(profile)
-- VALUES ( '{
--       "name" : "Mohamed Abdullahi",
--       "JsonToken" : "jalsf3402159fkas_fm39050125",
--       "Address" : "7384 Imperial DR AVE N MINNEAPOLIS< MNS"
-- }');
--
-- INSERT INTO users(profile)
-- VALUES ( '{
--   "name" : "Ahmed Abdullahi",
--   "JsonToken" : "jalsf3402159fkas_fm39050125",
--   "Address" : "7384 Imperial DR AVE N MINNEAPOLIS< MNS"
-- }');
--
--
-- INSERT INTO users(profile)
-- VALUES ( '{
--   "name" : "Ahmed Abdullahi",
--   "JsonToken" : "jalsf3402159fkas_fm39050125",
--   "Refered" : {
--       "name":"Ahed SImaisl"
--   },
--   "Address" : "7384 Imperial DR AVE N MINNEAPOLIS< MNS"
-- }');
--
-- INSERT INTO users(profile)
-- VALUES ( '{
--   "name" : "Ahmed Abdullahi",
--   "JsonToken" : "jalsf3402159fkas_fm39050125",
--   "Refered" : {
--     "name":"Ahed SImaisl"
--   },
--   "cities" : ["Boston", "Chicagi"],
--   "Address" : "7384 Imperial DR AVE N MINNEAPOLIS< MNS"
-- }');
--
--
--
-- SELECT u.id, u.profile::jsonb FROM users u;
--
-- SELECT '{
--   "user": {
--     "id": 1,
--     "roles": ["admin", "editor"]
--   }
-- }'::jsonb as profile;
--
--
-- SELECT  FROM users u where profile['id'] = 2;
--
-- SELECT * FROM USERS
-- WHERE profile['name'] = '"Mohamed Abdullahi"';
--
-- SELECT *
-- FROM users
-- WHERE profile <@ '{"id": 2}';
--
-- EXPLAIN ANALYSE
-- SELECT * FROM USERS
-- WHERE profile['name'] = '"Mohamed Abdullahi"';
-- -- Seq Scan on users  (cost=0.00..25.88 rows=6 width=36) (actual time=0.016..0.025 rows=1 loops=1)
-- -- "  Filter: (profile['name'::text] = '""Mohamed Abdullahi""'::jsonb)"
-- --   Rows Removed by Filter: 1
-- -- Planning Time: 0.067 ms
-- -- Execution Time: 0.038 ms
-- CREATE INDEX idx_users_profile
--     ON users USING GIN (profile->>'name');
--
-- -- RETURNS JSON
-- EXPLAIN ANALYSE
-- SELECT users.profile #> '{Refered, name}' AS ADDRESS from users;
--
-- SELECT profile ->  'cities' -> 0 AS ADDRESS from users WHERE profile['name'] = '"Ahmed Abdullahi"' ORDER BY  ADDRESS asc limit 1 ;
--
-- SELECT jsonb_agg(profile)
-- FROM users
--     WHERE profile['name'] = '"Mohamed Abdullahi"'
--
--
-- SELECT * FROM departments;
--
-- SELECT  jsonb_build_object('department', jsonb_build_object(
--         'id', d.id, 'dept_name', d.dept_name, 'location',  d.location
--                                          ))
-- FROM departments d
--
--
-- SELECT to_json(d) FROM departments d
-- WHERE d.dept_name = 'Sales';
--
-- SELECT jsonb_agg(d) FROM departments d
-- WHERE d.dept_name = 'Sales'
--
--
-- SELECT id, first_name, last_name, hire_date,
--        CASE
--            WHEN extract(YEAR FROM hire_date) = 2020 THEN 'last Year'
--            ELSE 'This Year'
-- END as grade
-- FROM employees;
--
-- EXPLAIN ANALYSE
-- SELECT e.id, e.first_name, e.salary FROM employees e
-- WHERE e.first_name = 'John';
--
-- -- Seq Scan on employees e  (cost=0.00..11.88 rows=1 width=134) (actual time=0.062..0.065 rows=1 loops=1)
-- --   Filter: ((first_name)::text = 'John'::text)
-- --   Rows Removed by Filter: 13
-- -- Planning Time: 0.160 ms
-- -- Execution Time: 0.100 ms
--
--
--
-- CREATE index find_employee_by_name ON employees(first_name);
-- CREATE index find_employee_by_id ON employees(id);
--
-- -- Seq Scan on employees e  (cost=0.00..1.18 rows=1 width=138) (actual time=0.026..0.029 rows=1 loops=1)
-- --   Filter: (id = 1)
-- --   Rows Removed by Filter: 13
-- -- Planning Time: 0.097 ms
-- -- Execution Time: 0.056 ms
--
--
-- EXPLAIN ANALYSE
-- SELECT e.id,  e.first_name, e.salary FROM employees e
-- WHERE e.id = 1;
--
-- -- Seq Scan on employees  (cost=0.00..1.18 rows=1 width=486) (actual time=3.488..3.493 rows=4 loops=1)
-- --   Filter: (department_id = 2)
-- --   Rows Removed by Filter: 10
-- -- Planning Time: 3.567 ms
-- -- Execution Time: 3.546 ms
--
-- -- Seq Scan on employees  (cost=0.00..1.18 rows=1 width=486) (actual time=0.015..0.018 rows=4 loops=1)
-- --   Filter: (department_id = 2)
-- --   Rows Removed by Filter: 10
-- -- Planning Time: 0.126 ms
-- -- Execution Time: 0.035 ms
--
--
-- EXPLAIN ANALYSE
-- SELECT *
-- FROM employees
-- WHERE department_id = 2;
--
-- CREATE INDEX  find_employee_by_dep_id ON Employees(department_id);
--
--
-- EXPLAIN ANALYSE
-- SELECT e.first_name, e.last_name, d.dept_name
-- FROM employees e
--          JOIN departments d ON e.department_id = d.id;
--
-- -- Seq Scan on orders  (cost=0.00..1.25 rows=1 width=86) (actual time=0.012..0.015 rows=3 loops=1)
-- --   Filter: (customer_id = 1)
-- --   Rows Removed by Filter: 17
-- -- Planning Time: 0.116 ms
-- -- Execution Time: 0.068 ms
--
--
--
--
-- CREATE INDEX find_order_by_customer_id ON orders(customer_id);
--
-- EXPLAIN ANALYSE
-- SELECT *
-- FROM orders
-- WHERE customer_id = 1;
--
--
-- CREATE INDEX find_common ON products(id, category_id);
--
-- EXPLAIN ANALYSE
-- SELECT * FROM products
-- WHERE id = 1 AND category_id = 1;
--
--
-- CREATE INDEX find_order_by_date ON ORDERS(customer_id, order_date DESC);
--
-- -- BEFORE CREATEING INDEX--
-- -- Sort  (cost=1.31..1.31 rows=1 width=86) (actual time=0.036..0.037 rows=3 loops=1)
-- --   Sort Key: order_date DESC
-- --   Sort Method: quicksort  Memory: 25kB
-- --   ->  Seq Scan on orders  (cost=0.00..1.30 rows=1 width=86) (actual time=0.015..0.019 rows=3 loops=1)
-- --         Filter: ((order_date >= '2023-01-01'::date) AND (customer_id = 1))
-- --         Rows Removed by Filter: 17
-- -- Planning Time: 0.120 ms
-- -- Execution Time: 0.058 ms
--
-- --AFTER CRETING INDEX
-- -- Sort  (cost=1.31..1.31 rows=1 width=86) (actual time=0.045..0.046 rows=3 loops=1)
-- --   Sort Key: order_date DESC
-- --   Sort Method: quicksort  Memory: 25kB
-- --   ->  Seq Scan on orders  (cost=0.00..1.30 rows=1 width=86) (actual time=0.031..0.037 rows=3 loops=1)
-- --         Filter: ((order_date >= '2023-01-01'::date) AND (customer_id = 1))
-- --         Rows Removed by Filter: 17
-- -- Planning Time: 0.160 ms
-- -- Execution Time: 0.072 ms
-- SET enable_seqscan = ON;
--
--
-- EXPLAIN ANALYSE
-- SELECT *
-- FROM orders
-- WHERE customer_id = 1
--   AND order_date >= '2023-01-01'
-- ORDER BY order_date DESC;
--
-- ANALYZE orders;
--
-- CREATE INDEX find_total ON orders(id, customer_id , total_amount);
-- --  BEFORE
-- -- Index Scan using orders_pkey on orders  (cost=0.43..8.45 rows=1 width=27) (actual time=0.511..0.513 rows=1 loops=1)
-- --   Index Cond: (id = 1)
-- --   Filter: ((total_amount > '1000'::numeric) AND (customer_id = 1) AND ((status)::text = 'Delivered'::text))
-- -- Planning Time: 0.181 ms
-- -- Execution Time: 0.545 ms
--
-- --     AFTER
-- -- Index Scan using find_total on orders  (cost=0.43..8.45 rows=1 width=27) (actual time=0.033..0.034 rows=1 loops=1)
-- --   Index Cond: ((id = 1) AND (customer_id = 1) AND (total_amount > '1000'::numeric))
-- --   Filter: ((status)::text = 'Delivered'::text)
-- -- Planning Time: 0.373 ms
-- -- Execution Time: 0.062 ms
--
-- -- Index Scan using find_total on orders  (cost=0.43..8.45 rows=1 width=27) (actual time=3.313..3.317 rows=1 loops=1)
-- --   Index Cond: (id = 1)
-- -- Planning Time: 0.557 ms
-- -- Execution Time: 3.386 ms
--
-- EXPLAIN ANALYSE
-- SELECT * FROM orders
-- WHERE id = 1;
--
--
-- --   AND
-- --       customer_id = 1 AND
-- --       total_amount > 1000 AND
-- --       status = 'Delivered';
--
--
-- SET enable_seqscan  = ON;
--
-- --Index Scan using find_by_id_king on orders  (cost=0.43..8.45 rows=1 width=27) (actual time=0.044..0.045 rows=1 loops=1)
-- -- Index Cond: (id = 1)
-- -- Planning Time: 0.143 ms
-- -- Execution Time: 0.068 ms
--
-- CREATE INDEX find_by_id_king ON orders USING btree(id);
-- EXPLAIN ANALYSE
-- SELECT * FROM orders
-- WHERE id = 1;
-- SET enable_indexscan =ON;
--
--
--
-- -- Index Scan using find_by_id_king_23 on orders  (cost=0.00..8.02 rows=1 width=27) (actual time=0.019..0.020 rows=1 loops=1)
-- --   Index Cond: (id = 1)
-- -- Planning Time: 2.141 ms
-- -- Execution Time: 0.049 ms
--
-- DROP INDEX find_by_id_king_23;
-- CREATE INDEX find_by_id_king_23 ON orders USING hash (id)
--
--
--
--
--
--
